name: "Publish New Draft Version"

on:
  push:
    tags:
      - "draft-*"
  workflow_dispatch:
    inputs:
      email:
        description: "Submitter email"
        default: ""
        type: string

jobs:
  build:
    name: "Publish New Draft Version"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v6
      with:
        # Needed for tracing file history for replacement status
        fetch-depth: 0
        fetch-tags: true

    # See https://github.com/actions/checkout/issues/290
    - name: "Get Tag Annotations"
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}

    - name: "Setup"
      id: setup
      run: date -u "+date=%FT%T" >>"$GITHUB_OUTPUT"

    - name: "Caching"
      uses: actions/cache@v5
      with:
        path: |
          .refcache
          .venv
          .gems
          node_modules
          .targets.mk
        key: i-d-${{ steps.setup.outputs.date }}
        restore-keys: i-d-

    - name: "Build Drafts"
      id: build
      uses: martinthomson/i-d-template@v1
      with:
        make: releases
        token: ${{ github.token }}

    - name: "Upload to Datatracker"
      uses: martinthomson/i-d-template@v1
      with:
        make: upload
      env:
        UPLOAD_EMAIL: ${{ inputs.email }}
        GITHUB_STEP: upload

    - name: "Archive Submitted Drafts"
      uses: actions/upload-artifact@v6
      if: always() && steps.build.outcome == 'success'
      with:
        name: published
        path: "versioned/draft-*-[0-9][0-9].*"
